name: Build Windows Curses Wheels

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Chocolatey
      shell: powershell
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; `
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; `
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    - name: Install Visual Studio Build Tools
      shell: cmd
      run: |
        choco install visualstudio2022buildtools --confirm --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --includeOptional"

    - name: Install CMake
      shell: cmd
      run: |
        choco install cmake --confirm

    - name: Verify CMake Installation
      shell: cmd
      run: cmake --version

    - name: Initialize Developer Command Prompt
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat"

    - name: Check PATH
      shell: cmd
      run: echo %PATH%

    - name: Check cl.exe Path
      shell: cmd
      run: dir "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\*\bin\Hostx64\x64\cl.exe"

    - name: Install setuptools and wheel for Python 3.12
      shell: cmd
      run: |
        py -3.12 -m pip install --upgrade pip setuptools wheel

    - name: Build wheels
      shell: cmd
      run: |
        git submodule update --init --recursive
        ./build-wheels.bat 3.12

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows-curses-wheel
        path: dist/*.whl
